#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
import time
import layint_runtime_api
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--name", help="Name for image", required=True)
parser.add_argument("--description", help="Description for image")
parser.add_argument("--registry", help="Name of registry image is stored in", required=True)
parser.add_argument("--push-registry", help="Name of registry to push layered image", required=False)
parser.add_argument("--push-name", help="Name for image to push", required=False)
parser.add_argument("--config", help="Name of configuration to apply to image", required=False)
parser.add_argument("--configid", help="ID of configuration to apply to image", required=False)
parser.add_argument("--policy", help="Name of security policy to apply to image", required=False)
parser.add_argument("--policyid", help="ID of security policy to apply to image", required=False)
parser.add_argument("--imageid", help="Database ID for image (for advanced users only)")
parser.add_argument("--instrument", help="Instrument image", action="store_true", required=False)
parser.add_argument("--wait", help="Wait for instrumentation to complete", action="store_true", required=False)
args = parser.parse_args()

if args.policy is None and args.policyid is None:
    print("--policy or --policyid required\n")
    print(parser.print_help())
    sys.exit(1)

if args.policy is not None and args.policyid is not None:
    print("--policy cannot be used with --policyid\n")
    print(parser.print_help())
    sys.exit(1)

# image.configid can be empty, and then the default config will be used

if args.config is not None and args.configid is not None:
    print("--config cannot be used with --configid\n")
    print(parser.print_help())
    sys.exit(1)

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
registry_api = layint_runtime_api.RegistryApi()
registry_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Looking up registry '%s' on API host %s..." % (args.registry, v.get("api_host")))
try:
    registry = registry_api.get_registry_by_name(args.registry)
except ApiException as e:
    print("Exception when calling RegistryApi->get_registry_by_name: %s\n" % e)
    sys.exit(1)

push_registry=None
if args.push_registry is not None:
    try:
        push_registry = registry_api.get_registry_by_name(args.push_registry)
    except ApiException as e:
        print("Exception when calling RegistryApi->get_registry_by_name: %s\n" % e)
        sys.exit(1)

config = None
if args.config is not None or args.configid is not None:
    config_api = layint_runtime_api.ConfigurationApi()

    try:
        if args.configid is not None:
            if args.verbose:
                print("Looking up configid %s on API host %s..." % (args.configid, v.get("api_host")))
            config = config_api.get_config(args.configid)
        else:
            if args.verbose:
                print("Looking up config '%s' on API host %s..." % (args.config, v.get("api_host")))
            config = config_api.get_config_by_name(args.config)
    except ApiException as e:
        if args.configid is not None:
            print("Unable to get config with id %s:%s\n" % (args.configid, e))
        else:
            print("Unable to get config named '%s':%s\n" % (args.config, e))
        sys.exit(2)

policy_api = layint_runtime_api.PolicyApi()

try:
    policy = None
    if args.policyid is not None:
        if args.verbose:
            print("Looking up policyid %s on API host %s..." % (args.policyid, v.get("api_host")))
        policy = policy_api.get_policy(args.policyid)
    else:
        if args.verbose:
            print("Looking up policy '%s' on API host %s..." % (args.policy, v.get("api_host")))
        policy = policy_api.get_policy_by_name(args.policy)
except ApiException as e:
    if args.policyid is not None:
        print("Unable to get policy with id %s:%s\n" % (args.policyid, e))
    else:
        print("Unable to get policy named '%s':%s\n" % (args.policy, e))
    sys.exit(3)

# Image
image_api = layint_runtime_api.ImageApi()
image_api.api_client.host = v.get("api_host")
image = layint_runtime_api.Image()
image.name = args.name
image.description = args.description
image.registry = registry.id
if config is not None:
    image.config_id = config.id
image.policy_id = policy.id

if args.imageid:
    image.id = args.imageid

if args.push_registry is not None:
    image.push_registry = push_registry.id
    if args.push_name is not None:
        image.push_name = args.push_name
    else:
        # fall back to original image name
        print("Using original image name in push registry since push-name not specified: %s/%s" % (push_registry.url, image.name))
        image.push_name = image.name

instrument = "false"
if args.instrument:
    instrument = "true"

# Create new Image definition
if args.verbose:
    print("Creating Image %s on API host %s..." % (args.name, v.get("api_host")))
try:
    api_response = image_api.add_image(image=image, instrument_image=instrument)
    image.id = api_response.id
except ApiException as e:
    print("Exception when calling ImageApi->add_image: %s\n" % e)
    sys.exit(1)

if args.verbose:
    print("Image created, ID " + str(image.id))
else:
    # required for li_instrument
    print(str(image.id))

if args.wait:
    instrumented = False
    while instrumented != True:
        if args.verbose:
            print("Waiting for instrumentation of Image %s. Current status: %s" % (image.id, image.status_msg))
            # Flush output so it's seen in active build logs
            sys.stdout.flush()
        try:
            image = image_api.get_image(image.id)
            if image.status_msg == "OK":
                instrumented = True
            else:
                time.sleep(5)
        except ApiException as e:
            print("Exception when calling ImageApi->get_image: %s\n" % e)
            sys.exit()

    if args.verbose:
        print("Final image status: " + image.status_msg)
