#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_runtime_api
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--name", help="Name for policy")
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
policy_api = layint_runtime_api.PolicyApi()
policy_api.api_client.host = v.get("api_host")

policy = layint_runtime_api.Policy()
if args.name:
    policy.name = args.name
else:
    policy.name = "Protect passwd"
policy.description = "Blocks processes from reading /etc/passwd"
policy.default_file_action = "allow"
policy.default_network_action = "allow"
policy.default_program_action = "allow"
policy.schema_version = "v1.0"
policy.suspend = False
policy.rules = []
passwd_rule = layint_runtime_api.PolicyRule()
passwd_rule.name = "No reading /etc/passwd"
passwd_rule.rule_type = "syscall"
passwd_rule.program = "/bin/cat"
passwd_rule.syscall = 2
passwd_rule.arg1 = "/etc/passwd"
passwd_rule.action = "deny"
policy.rules.append(passwd_rule)

# Create new Policy definition
if args.verbose:
    print("Creating Policy %s on API host %s..." % (policy.name, v.get("api_host")))
try:
    api_response = policy_api.add_policy(policy=policy)
    policy.id = api_response.id
    if args.verbose:
        pprint(api_response)
except ApiException as e:
    print("Exception when calling PolicyApi->add_policy: %s\n" % e)
    sys.exit()

if args.verbose:
    print("Policy created, ID " + str(policy.id))
