#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import swagger_client
from swagger_client.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

env_setup()

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--id", help="Id for config", required=True)
args = parser.parse_args()

swagger_client.configuration.api_key['Authorization'] = v.get("api_key")
config_api = swagger_client.ConfigurationApi()
config_api.api_client.host = v.get("api_host")

# Delete config by ID
if args.verbose:
    print("Deleting Config by ID %s on API host %s..." % (args.id, v.get("api_host")))
try:
    api_response = config_api.delete_config(args.id)
    if args.verbose:
        pprint(api_response)
except ApiException as e:
    print("Exception when calling ConfigApi->delete_config: %s" % e)
    sys.exit()

if args.verbose:
    print("Config deleted, ID " + str(args.id))
