#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_runtime_api
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--name", help="Name for registry", required=True)
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
registry_api = layint_runtime_api.RegistryApi()
registry_api.api_client.host = v.get("api_host")

# Get registry by name
if args.verbose:
    print("Getting Registry by name \"%s\" on API host %s..." % (args.name, v.get("api_host")))
try:
    registry = registry_api.get_registry_by_name(args.name)
    if args.verbose:
        pprint(registry)
except ApiException as e:
    print("Exception when calling RegistryApi->get_registry_by_name: %s" % e)
    sys.exit()

# Delete registry by ID
if args.verbose:
    print("Deleting Registry by ID %s on API host %s..." % (registry.id, v.get("api_host")))
try:
    api_response = registry_api.delete_registry(registry.id)
    if args.verbose:
        pprint(api_response)
except ApiException as e:
    print("Exception when calling RegistryApi->delete_registry: %s" % e)
    sys.exit()

if args.verbose:
    print("Registry deleted, ID " + str(registry.id))
