#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
import layint_runtime_api
from pprint import pprint
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--policyid", help="ID of policy to get", required=True)
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
# layint_runtime_api.configuration.debug = True
policy_api = layint_runtime_api.PolicyApi()
policy_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Looking up policy %s on API host %s..." % (args.policyid, v.get("api_host")))
try:
    policy = policy_api.get_policy(args.policyid)
except ApiException as e:
    print("Exception when calling PolicyAPI->get_policy: %s\n" % e)
    sys.exit()

if args.verbose:
    print("policy detail:")
    print(" Name: %s" % (policy.name))
    print(" ID: %s" % (policy.id))
    print(" Description: %s" % (policy.description))
    print(" User ID: %s" % (policy.user_id))
    print(" Group ID: %s" % (policy.group_id))
    print(" Schema Version: %s" % (policy.schema_version))
    print("")
    # pprint(policy)

print(" %s - %s - %s" % (policy.id, policy.name, policy.description))

# print verbose info in csv format so rules could be placed into a policy.csv
if args.verbose:
    ctr = 1
    print("policy.rules:")
    for rule in policy.rules:
        #if rule.syscall == 500: # option to ignore getnameinfo
        #    continue
        actionInt = 0
        if rule.action == "allow":
            actionInt = 1
        #if rule.rule_type.lower() == "listener" or rule.rule_type.lower() == "execution":
        #rule_name = "rule #%d" % (ctr)
        rule_name=""
        print("%s,%s,%s,%s,%s,%s,%s," % (rule_name, rule.program, actionInt, rule.syscall, rule.arg1, rule.arg2, rule.arg3)) #rule.file))
        ctr = ctr + 1
