#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
import layint_runtime_api
from pprint import pprint
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--configid", help="ID of config to get", required=True)
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
# layint_runtime_api.configuration.debug = True
config_api = layint_runtime_api.ConfigurationApi()
config_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Looking up config %s on API host %s..." % (args.configid, v.get("api_host")))
try:
    config = config_api.get_config(args.configid)
except ApiException as e:
    print("Exception when calling ConfigurationApi->get_config: %s\n" % e)
    sys.exit()

if args.verbose:
    print("config detail:")
    pprint(config)

print(" %s - %s" % (config.id, config.name))
