#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import swagger_client
from swagger_client.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

env_setup()

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
args = parser.parse_args()

swagger_client.configuration.api_key['Authorization'] = v.get("api_key")
config_api = swagger_client.ConfigurationApi()
config_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Getting Policies on API host %s..." % (v.get("api_host")))
try:
    configs = config_api.list_all_configurations()
    if args.verbose:
        pprint(configs)
except ApiException as e:
    print("Exception when calling ImageApi->get_images: %s" % e)
    sys.exit()

for config in configs:
    print("  %s" % (config['Name']))
