#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_runtime_api
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
image_api = layint_runtime_api.ImageApi()
image_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Getting Images on API host %s..." % (v.get("api_host")))
    print("\tadditional image detail available via `li_get_image`")
try:
    images = image_api.get_images()
    if args.verbose:
        pprint(images)
except ApiException as e:
    print("Exception when calling ImageApi->get_images: %s" % e)
    sys.exit()

for image in images:
    print(" %s - %s - %s" % (image['Id'], image['Name'], image['StatusMsg']))
