#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_runtime_api
from layint_runtime_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
args = parser.parse_args()

env_setup()

layint_runtime_api.configuration.api_key['Authorization'] = v.get("api_key")
container_api = layint_runtime_api.ContainerApi()
container_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Getting Containers on API host %s..." % (v.get("api_host")))
try:
    containers = container_api.get_containers()
except ApiException as e:
    print("Exception when calling ConfigurationApi->list_all_configurations(): %s" % e)
    sys.exit()

if args.verbose:
    pprint(containers)

for container in containers:
    print(" %s - %s - %s - %s" % (container['Id'], container['Status'], container['Location'], container['Application']))
    # pprint(container)
